services:
  - type: web
    name: Fort Inform Site
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      # Generate the Laravel APP_KEY on first deploy
      - key: APP_KEY
        generateValue: true
      # The public-facing URL of your app
      - key: APP_URL
        value: https://fort-inform-site.onrender.com
      # The database connection details
      - key: DATABASE_URL
        fromDatabase:
          name: Fort-Inform-Site-DB
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql

databases:
  # The PostgreSQL database
  - name: Fort-Inform-Site-DB
    databaseName: fort_inform_site_db
    user: fort_inform_user
    plan: free
