services:
  - type: web
    name: Fort-Inform
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Fort-Inform-DB
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql

databases:
  - name: Fort-Inform-DB
    databaseName: fort_inform_db
    user: fort_inform_user
    plan: free
